name: Validate composer.json and composer.lock

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: List all files in the directory for debugging
      - name: List files in workspace
        run: ls -la

      # Step 3: Validate composer.json
      - name: Validate composer.json
        run: composer validate --strict
