name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      # Install dependencies
      - name: Install dependencies
        run: composer install

      # List files to ensure composer.json exists
      - name: List files in workspace
        run: ls -la

      # Validate composer.json
      - name: Validate composer.json
        run: composer validate --strict
